
### User Info
GET http://localhost:3000/api/v1/user

### total repos
GET http://localhost:3000/api/v1/repos

### 
// commits
GET http://localhost:3000/api/v1/commits

### languages
GET http://localhost:3000/api/v1/languages

### achievements
GET http://localhost:3000/api/v1/achievements

### invalid route
GET http://localhost:3000/api/v1/something